### ISSUE TITLE
man: Obsolete 'installCompEnv' reference

### ISSUE THREAD

**Issue by juliangehring** [gmbecker/switchr#1]
The help for `switchTo`refers to `installCompEnv` for details, but this was removed from the package.

**Comment by gmbecker** [comment]
Julian,

I suspect its actually just been renamed, but I'll track this down and get
it fixed.

Thanks,
~G

On Thu, Jan 8, 2015 at 10:48 AM, Julian Gehring notifications@github.com
wrote:

> The help for switchTorefers to installCompEnv for details, but this was
> removed from the package.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gmbecker/switchr/issues/1.

## 

Gabriel Becker, PhD
Alumnus
Statistics Department
University of California, Davis

**Comment by dracodoc** [comment]
I'm still see this reference today and got confused. I guess it should be `makeLibraryCtx` now.
